### ISSUE TITLE
Issue loading /demo.html and /

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#100]
After the initial run, index.html works but loading demo.html gives the following error

`Traceback (most recent call last):
  File "/Users/andrewtran/Documents/Neon.js/app_env/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/andrewtran/Documents/Neon.js/neonsrv/interface.py", line 48, in get
    squarenotefiles=self.get_files('squarenote'),
  File "/Users/andrewtran/Documents/Neon.js/neonsrv/interface.py", line 19, in get_files
    for f in os.listdir(mei_dir):
OSError: [Errno 2] No such file or directory: '/Users/andrewtran/Documents/Neon.js/squarenote'`

**Comment by ATranimal** [comment]
Same error happens on the root url as well

**Comment by ATranimal** [comment]
Fixed with commit #1bf5a13e071dfd9c28dfff7bbd2df0b68636e2f4
